[versions]
androidx-core = "1.10.1"
androidx-activity = "1.7.2"
androidx-lifecycle = "2.6.1"
androidx-compose-bom = "2023.10.0"
androidx-compose-material3 = "1.1.0"
firebase-auth-ktx = "22.0.0"
firebase-firestore-ktx = "24.7.1"

[libraries]
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-compose = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose-bom" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-compose-material3" }
firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx", version.ref = "firebase-auth-ktx" }
firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx", version.ref = "firebase-firestore-ktx" }

